### ISSUE TITLE
runit() function fails on est=TRUE

### ISSUE THREAD

**Issue by jimianelli** [SPRFMO/jjmr#2]
says can't find control file but it's there...

**Comment by jimianelli** [comment]
runit("mod1.18",pdf=TRUE,portrait=F,est=TRUE,exec="jjms")
 does work now...failed before because I left off "exec="jjms"...default is "jjm" the single stock version

**Comment by roliveros-ramos** [comment]
new default is set to "jjms" with a message. Error if the executable is not found.
